### ISSUE TITLE
XW Investigator psooible?

### ISSUE THREAD

**Issue by Maddin81** [forensenellanebbia/xways-forensics#2]
In X-ways forensics INVESTIGATOR there is not User.txt only "File Type Categories.txt" the "File Type Categories **User**.txt" is missing. Is it possible to get those custom filters in investogator??

**Comment by forensenellanebbia** [comment]
I've never used `X-Ways Investigator` and don't know what `User.txt` is. I just tried with `X-Ways Forensics (19.8 SR13)`, changed the GUI to `X-Ways Investigator`, restarted and opened a case. I was still able to see and use my filters.
